---
- hosts: localhost
  vars:
    package_name: 'netagent-{{netagent_version}}.tar.gz'
  gather_facts: no
  tasks:
    - name: Download package to localhost
      delegate_to: localhost
      shell: "test -e ./{{package_name}} || curl -O https://www.banyanops.com/netting/{{package_name}}"
      register: download_result
      changed_when: download_result.stdout != ""
- hosts: all
  vars:
    package_name: 'netagent-{{netagent_version}}.tar.gz'
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Install python for Ansible
      raw: "command -v python > /dev/null || (apt -y update && apt install -y python-minimal)"
      register: output
      changed_when: output.stdout != ""
  tasks:
    - name: Create banyan-packages
      file:
        name: /opt/banyan-packages
        state: directory
    - name: Install jq utility
      copy:
        src: bin/jq-1.5/jq-linux64
        dest: /usr/bin/jq
        mode: 0755
    - name: Copy package
      unarchive:
        src: "./{{package_name}}"
        dest: "/opt/banyan-packages"
    - name: Copy config
      template:
        src: ./templates/config.yaml.tpl.j2
        dest: /opt/banyan-packages/netagent-{{netagent_version}}/config.yaml.tpl
    - name: Run configure-bootstrap
      command: /opt/banyan-packages/netagent-{{netagent_version}}/configure-bootstrap '{{refresh_token}}' {{cluster_name}}
#      environment:
#        BANYAN_API: '{{banyan_api}}'
    - name: Run setup-netagent
      command: /opt/banyan-packages/netagent-{{netagent_version}}/setup-netagent.sh
