apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: banyan-netagent
  labels:
    app: banyan-platform
    version: v1

spec:
  template:
    metadata:
      labels:
        name: banyan-netagent
    spec:
        hostNetwork: true
        hostPID: true
        containers:
          - image: pub.banyanops.com/k8s-netagent:0.7.4
            imagePullPolicy: Always
            name: netagent
            securityContext:
              privileged: true
            volumeMounts:
              - name: etc
                mountPath: /etc
                readOnly: true
              - name: kernel-debug
                mountPath: /sys/kernel/debug
              - name: dockersock
                mountPath: /var/run/docker.sock
              - name: banyan-dir
                mountPath: /root/.banyan
                readOnly: false 
              - name: netagent-config
                mountPath: /secret
                readOnly: true
            env:
              - name: NETAGENT_CONFIG
                value: /secret/config.yaml
              - name: GET_HOSTS_FROM
                value: dns
                # If your cluster config does not include a dns service, then to
                # instead access environment variables to find service host
                # info, comment out the 'value: dns' line above, and uncomment the
                # line below.
                # value: env
              - name: BANYAN_HOST_DIR
                value: /root/.banyan
            lifecycle:
              preStop:
                exec:
                  command: ["/opt/banyan/on-stop.sh"]
          # These containers are run during pod initialization
        initContainers:
        - name: init-agent
          image: pub.banyanops.com/k8s-netagent:0.7.4
          command: ["/opt/banyan/on-start.sh"]
          imagePullPolicy: Always
          securityContext:
              privileged: true
          volumeMounts:
          - name: netagent-config
            mountPath: /secret
            readOnly: true
        volumes:
          - name: etc
            hostPath:
              path: /etc
          - name: kernel-debug
            hostPath:
              path: /sys/kernel/debug
          - name: banyan-dir
            hostPath:
              path: /tmp     
          - name: dockersock
            hostPath:
              path: /var/run/docker.sock
          - name: netagent-config
            secret:
              secretName: netagent-config
