apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: banyan-netagent

spec:
  template:
    metadata:
      labels:
        com.banyanops.agent: netagent
        com.banyanops.app: banyan-platform
    
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostPID: true
      
      volumes:
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
      - name: banyan-dir
        hostPath:
          path: /tmp     
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: gpg-cidr
        secret:
          secretName: bnn-secrets      

      containers:
      - name: netagent
        image: pub.banyanops.com/k8s-netagent:0.5.0-rc5
        imagePullPolicy: Always
        securityContext:
          privileged: true        
        args:
        - "--hostOnly" 
        - "--kubelet"
        - "--kubeletAddr=http://localhost:10255"
        - "shield-ca:1200"
        volumeMounts:
          - name: kernel-debug
            mountPath: /sys/kernel/debug
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: banyan-dir
            mountPath: /root/.banyan
            readOnly: false 
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        - name: BANYAN_HOST_DIR
          value: /root/.banyan
        lifecycle:
          preStop:
            exec:
              command: ["/opt/banyan/on-stop.sh"]
      
      initContainers:
      - name: init-agent
        image: pub.banyanops.com/k8s-netagent:0.5.0-rc5
        command: ["/opt/banyan/on-start.sh"]
        imagePullPolicy: Always
        securityContext:
            privileged: true
        volumeMounts:
        - name: gpg-cidr
          mountPath: /secret
          readOnly: true    
