apiVersion: v1
kind: Service
metadata:
  name: banyan-shield-ca

spec:
  type: ClusterIP
  # UPDATEME: clusterIP should be a valid number within the Service ClusterIP Range
  clusterIP: 10.0.0.111
  ports:
  - port: 1200
  selector:
    com.banyanops.agent: shield

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: banyan-shield-ca

spec:
  replicas: 1
  template:
    metadata:
      labels:
        com.banyanops.agent: shield
        com.banyanops.app: banyan-platform
    
    spec:
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: banyan-dir
        hostPath:
          path: /tmp   
      - name: kubeconfig-dir
        hostPath:
          #path: /home/azureuser/.kube
          path: /tmp
      - name: keystore-dir
        emptyDir: {}
        #hostPath:
        #  path: /tmp #/.banyan/keystore

      containers:
      - name: shield
        image: pub.banyanops.com/shield:incluster
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        - name: BANYAN_HOST_DIR
          value: /root/.banyan
        # UPDATEME: ORG_ID's value is a 32-char string available in your Web Dashboard
        - name: ORG_ID
          value: aaaaaaaa-bbbb-cccc-0000-111122223333
        args:
        # UPDATEME: clustername should be the same as in your cfgfile
        - "--banyanURL=https://stage.banyanops.com:443/api_server_host_v1"
        - "--clustermanager=kubernetes"
        - "--cfgfile=/root/.kube/config"
        - "--clustername=MyKubeCluster"
        - "--groupType=test"
        - "--cloglevel=DEBUG"
        - "--floglevel=DEBUG"      
        ports:
        - containerPort: 1200
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
          readOnly: false
        - mountPath: /banyandir
          name: banyan-dir
          readOnly: false  
        - mountPath: /root/.kube
          name: kubeconfig-dir
          readOnly: true
      - name: cfssl
        image: cfssl/cfssl:1.2.0
        imagePullPolicy: IfNotPresent
        args: 
        - "serve" 
        - "-config=/etc/cfssl/root_config.json" 
        - "-ca=/etc/cfssl/ca.pem" 
        - "-ca-key=/etc/cfssl/ca-key.pem"
        volumeMounts:
        - name: keystore-dir
          mountPath: /etc/cfssl

      initContainers:
      - name: init-ca
        image: pub.banyanops.com/banyanops/init-ca
        imagePullPolicy: Always
        volumeMounts:
        - name: keystore-dir
          mountPath: /initca/keystore

      # UPDATEME: ensure Shield runs on your master
      # you can label the master and make it schedulable via these commands:
      #   kubectl label nodes master-0 shieldrunner=true
      #   kubectl patch node master-0 -p '{"spec":{"unschedulable":false}}'
      nodeSelector:
        shieldrunner: "true"
