---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install curl
      yum:
        name: curl
        state: present
    - name: Download jq
      get_url:
        url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
        dest: /usr/bin/jq
        mode: 0755
    - name: Install banyan-netagent
      package:
        name: https://www.banyanops.com/onramp/rpm/banyan-netagent-{{netagent_version}}.x86_64.rpm
        state: present
    - name: Copy config
      template:
        src: ./templates/config.yaml.tpl.j2
        dest: /opt/banyan-packages/config.yaml.tpl
    - name: Run post-install script
      shell: /opt/banyan-packages/install '{{refresh_token}}' {{cluster_name}}
      environment:
        BANYAN_API: "{{api_server}}"
