---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Install python for Ansible
      raw: "test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)"
      register: output
      changed_when: output.stdout != ""
    - setup:
  tasks:
    - group_by:
        key: os_{{ansible_distribution}}
- hosts: os_CentOS:os_RedHat:os_Amazon
  become: yes
  tasks:
    - name: Add Banyan public key
      rpm_key:
        state: present
        key: https://www.banyanops.com/onramp/repo/RPM-GPG-KEY-banyan
    - name: Add banyan repo
      yum_repository:
        name: banyan-prod
        description: banyan prod repo
        baseurl: https://www.banyanops.com/onramp/repo/
        gpgcheck: true
        gpgkey: https://www.banyanops.com/onramp/repo/RPM-GPG-KEY-banyan
- hosts: os_Ubuntu:os_Debian
  become: yes
  tasks:
    - debug:
        msg: "Note: Ubuntu/Debian support is WIP! Package signing and support for more distros coming soon."
    - name: Add banyan repo
      apt_repository:
        repo: "deb [trusted=yes] http://www.banyanops.com/onramp/repo xenial main"
        state: present
- hosts: all
  become: yes
  tasks:
    - name: Install jq utility
      copy:
        src: bin/jq-1.5/jq-linux64
        dest: /usr/bin/jq
        mode: 0755
    - name: Install packages
      package:
        name:
          - curl
          - banyan-netagent
        state: present
    - name: Copy config
      template:
        src: ./templates/config.yaml.tpl.j2
        dest: /opt/banyan-packages/config.yaml.tpl
    - name: Run post-install script
      shell: /opt/banyan-packages/install '{{refresh_token}}' {{cluster_name}}
#      environment: 
#        BANYAN_API: '{{banyan_api}}'
